# Dockerfile for ums-app (Nginx)
FROM nginx:latest

# Copy static files into Nginx's default HTML directory
COPY ./app /usr/share/nginx/html

# Expose port 80 (internal to container)
EXPOSE 80
